// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows; // ← fixed
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Firebase options for Windows desktop, using the web app credentials.
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu-omZIYEWFfq6gE1ZzPgXjchDmzW2LxA',
    appId:
        '1:456932364376:web:13d0a635ce1a1f9049fa2d', // ← fixed, removed duplicate prefix
    messagingSenderId: '456932364376',
    projectId: 'my-project-5449-1773395739847',
    storageBucket: 'my-project-5449-1773395739847.firebasestorage.app',
  );

  /// Firebase options for Android.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu-omZIYEWFfq6gE1ZzPgXjchDmzW2LxA',
    appId: '1:456932364376:android:f75848b793a8e34249fa2d',
    messagingSenderId: '456932364376',
    projectId: 'my-project-5449-1773395739847',
    storageBucket: 'my-project-5449-1773395739847.firebasestorage.app',
  );
}
