import 'package:rythmify/core/error/failures.dart';
import 'package:dartz/dartz.dart';

import '../entities/collection_type.dart';
import '../entities/playlist_entity.dart';
import '../repositories/playlist_repository.dart';

/// Creates a new playlist or album.
///
/// Validates that [name] is non-empty before delegating to the repository.
/// Stations cannot be created — they are generated by the backend.
///
/// Usage:
/// ```dart
/// final result = await createPlaylistUseCase(
///   name: 'Gym Mix',
///   isPublic: true,
///   type: CollectionType.playlist,
/// );
/// ```
class CreatePlaylistUseCase {
  const CreatePlaylistUseCase(this._repository);

  final PlaylistRepository _repository;

  Future<Either<Failure, PlaylistEntity>> call({
    required String name,
    required bool isPublic,
    CollectionType type = CollectionType.playlist,
  }) async {
    // ── Validation ────────────────────────────────────────────────────────
    final trimmed = name.trim();
    if (trimmed.isEmpty) {
      return const Left(
        PlaylistValidationFailure('Playlist name cannot be empty.'),
      );
    }
    if (trimmed.length > 100) {
      return const Left(
        PlaylistValidationFailure('Playlist name must be 100 characters or fewer.'),
      );
    }

    // Stations are read-only — this is a domain guard.
    if (type == CollectionType.station) {
      return const Left(
        PlaylistValidationFailure('Stations cannot be created manually.'),
      );
    }

    // ── Delegate ──────────────────────────────────────────────────────────
    return _repository.createPlaylist(
      name: trimmed,
      isPublic: isPublic,
      type: type,
    );
  }
}